### ISSUE TITLE
Lazyload Readspeaker js

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/readspeaker-helper#3]
The Javascript from Readspeaker is heavy and currently loaded on every page where the Lyssna button is available. I suggest that Readspeaker is initiated only when the Lyssna button is clicked.

**Comment by Svanmark** [comment]
We've noticed this as well and have tried to solve it. Unfortunately it seemed like the Readspekaer js did not work when loading it after page load.

Suggestions and pull request welcome if you have any idéas.

**Comment by perifer** [comment]
Ok, thanks for the info. I think I'll ask Readspeaker support to see if they have any suggestions.

**Comment by perifer** [comment]
Closed by https://github.com/helsingborg-stad/readspeaker-helper/issues/4. If get this in a tagged release I would be super happy. Might warrant a 2.0 release since it could break some existing sites that use the old classes.

**Comment by sebastianthulin** [comment]
I have made a tagged release with version number 2.0.0

**Comment by perifer** [comment]
Thanks!
